/// Pantry Constants and Data Structure
/// Defines the 3-layer category hierarchy for manual pantry entry
library;

class PantryCategory {
  final String title;
  final String icon;
  final List<PantrySubCategory> subCategories;

  const PantryCategory({
    required this.title,
    required this.icon,
    required this.subCategories,
  });

  Map<String, dynamic> toMap() {
    return {
      'title': title,
      'icon': icon,
      'subCategories': subCategories.map((x) => x.toMap()).toList(),
    };
  }

  factory PantryCategory.fromMap(Map<String, dynamic> map) {
    return PantryCategory(
      title: map['title'] as String? ?? '',
      icon: map['icon'] as String? ?? '',
      subCategories: List<PantrySubCategory>.from(
        (map['subCategories'] as List<dynamic>? ?? []).map<PantrySubCategory>(
          (x) => PantrySubCategory.fromMap(x as Map<String, dynamic>),
        ),
      ),
    );
  }
}

class PantrySubCategory {
  final String title;
  final List<String> items;

  const PantrySubCategory({required this.title, required this.items});

  Map<String, dynamic> toMap() {
    return {'title': title, 'items': items};
  }

  factory PantrySubCategory.fromMap(Map<String, dynamic> map) {
    return PantrySubCategory(
      title: map['title'] as String? ?? '',
      items: List<String>.from(map['items'] as List<dynamic>? ?? []),
    );
  }
}

// Comprehensive ingredient database with 500+ common items
const List<PantryCategory> kPantryCategories = [
  PantryCategory(
    title: 'Proteins',
    icon: '🥩',
    subCategories: [
      PantrySubCategory(
        title: 'Chicken',
        items: [
          'Chicken Breast',
          'Chicken Thighs',
          'Chicken Wings',
          'Chicken Drumsticks',
          'Whole Chicken',
          'Ground Chicken',
          'Chicken Tenders',
          'Rotisserie Chicken',
        ],
      ),
      PantrySubCategory(
        title: 'Beef',
        items: [
          'Ground Beef',
          'Ribeye Steak',
          'Sirloin Steak',
          'T-Bone Steak',
          'Filet Mignon',
          'Chuck Roast',
          'Beef Brisket',
          'Beef Ribs',
          'Stew Meat',
          'Beef Tenderloin',
        ],
      ),
      PantrySubCategory(
        title: 'Pork',
        items: [
          'Pork Chops',
          'Pork Loin',
          'Bacon',
          'Sausage',
          'Ham',
          'Pork Ribs',
          'Ground Pork',
          'Pork Tenderloin',
          'Pork Shoulder',
          'Pulled Pork',
        ],
      ),
      PantrySubCategory(
        title: 'Seafood',
        items: [
          'Salmon',
          'Tuna',
          'Shrimp',
          'Tilapia',
          'Cod',
          'Halibut',
          'Mahi Mahi',
          'Catfish',
          'Trout',
          'Crab',
          'Lobster',
          'Scallops',
          'Clams',
          'Mussels',
          'Calamari',
          'Anchovies',
        ],
      ),
      PantrySubCategory(
        title: 'Plant-Based',
        items: [
          'Tofu',
          'Tempeh',
          'Seitan',
          'Beyond Meat',
          'Impossible Meat',
          'Black Beans',
          'Chickpeas',
          'Lentils',
          'Kidney Beans',
          'Pinto Beans',
          'Edamame',
        ],
      ),
      PantrySubCategory(
        title: 'Deli & Processed',
        items: [
          'Turkey Slices',
          'Ham Slices',
          'Roast Beef Slices',
          'Salami',
          'Pepperoni',
          'Prosciutto',
          'Bologna',
          'Hot Dogs',
          'Bratwurst',
        ],
      ),
      PantrySubCategory(
        title: 'Other Meats',
        items: [
          'Lamb Chops',
          'Ground Lamb',
          'Duck',
          'Turkey Breast',
          'Ground Turkey',
          'Venison',
          'Rabbit',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Fruits',
    icon: '🍎',
    subCategories: [
      PantrySubCategory(
        title: 'Apples',
        items: [
          'Gala Apple',
          'Fuji Apple',
          'Honeycrisp Apple',
          'Granny Smith Apple',
          'Red Delicious Apple',
          'Golden Delicious Apple',
          'Pink Lady Apple',
          'Braeburn Apple',
        ],
      ),
      PantrySubCategory(
        title: 'Berries',
        items: [
          'Strawberries',
          'Blueberries',
          'Raspberries',
          'Blackberries',
          'Cranberries',
          'Gooseberries',
        ],
      ),
      PantrySubCategory(
        title: 'Citrus',
        items: [
          'Oranges',
          'Lemons',
          'Limes',
          'Grapefruit',
          'Tangerines',
          'Clementines',
          'Blood Oranges',
          'Kumquats',
        ],
      ),
      PantrySubCategory(
        title: 'Tropical',
        items: [
          'Bananas',
          'Pineapple',
          'Mango',
          'Kiwi',
          'Papaya',
          'Coconut',
          'Dragon Fruit',
          'Passion Fruit',
          'Guava',
          'Lychee',
          'Star Fruit',
        ],
      ),
      PantrySubCategory(
        title: 'Stone Fruits',
        items: ['Peaches', 'Nectarines', 'Plums', 'Cherries', 'Apricots'],
      ),
      PantrySubCategory(
        title: 'Melons',
        items: ['Watermelon', 'Cantaloupe', 'Honeydew', 'Casaba Melon'],
      ),
      PantrySubCategory(
        title: 'Other Fruits',
        items: [
          'Grapes',
          'Pears',
          'Pomegranate',
          'Figs',
          'Dates',
          'Persimmon',
          'Avocado',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Vegetables',
    icon: '🥦',
    subCategories: [
      PantrySubCategory(
        title: 'Leafy Greens',
        items: [
          'Spinach',
          'Kale',
          'Lettuce',
          'Romaine Lettuce',
          'Iceberg Lettuce',
          'Arugula',
          'Cabbage',
          'Red Cabbage',
          'Napa Cabbage',
          'Bok Choy',
          'Swiss Chard',
          'Collard Greens',
          'Mustard Greens',
        ],
      ),
      PantrySubCategory(
        title: 'Cruciferous',
        items: ['Broccoli', 'Cauliflower', 'Brussels Sprouts', 'Broccolini'],
      ),
      PantrySubCategory(
        title: 'Root Vegetables',
        items: [
          'Carrots',
          'Potatoes',
          'Sweet Potatoes',
          'Onions',
          'Red Onions',
          'Yellow Onions',
          'White Onions',
          'Shallots',
          'Garlic',
          'Beets',
          'Turnips',
          'Radishes',
          'Parsnips',
          'Ginger',
          'Yams',
        ],
      ),
      PantrySubCategory(
        title: 'Peppers',
        items: [
          'Bell Peppers',
          'Red Bell Pepper',
          'Green Bell Pepper',
          'Yellow Bell Pepper',
          'Orange Bell Pepper',
          'Jalapenos',
          'Serrano Peppers',
          'Habanero Peppers',
          'Poblano Peppers',
          'Anaheim Peppers',
          'Thai Chili',
        ],
      ),
      PantrySubCategory(
        title: 'Squash & Gourds',
        items: [
          'Zucchini',
          'Yellow Squash',
          'Cucumber',
          'Butternut Squash',
          'Acorn Squash',
          'Spaghetti Squash',
          'Pumpkin',
          'Kabocha Squash',
        ],
      ),
      PantrySubCategory(
        title: 'Mushrooms',
        items: [
          'Button Mushrooms',
          'Cremini Mushrooms',
          'Portobello Mushrooms',
          'Shiitake Mushrooms',
          'Oyster Mushrooms',
          'Enoki Mushrooms',
        ],
      ),
      PantrySubCategory(
        title: 'Tomatoes',
        items: [
          'Tomatoes',
          'Cherry Tomatoes',
          'Grape Tomatoes',
          'Roma Tomatoes',
          'Beefsteak Tomatoes',
          'Heirloom Tomatoes',
        ],
      ),
      PantrySubCategory(
        title: 'Other Vegetables',
        items: [
          'Celery',
          'Asparagus',
          'Green Beans',
          'Snap Peas',
          'Snow Peas',
          'Corn',
          'Eggplant',
          'Artichokes',
          'Leeks',
          'Scallions',
          'Chives',
          'Fennel',
          'Okra',
          'Water Chestnuts',
          'Bamboo Shoots',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Dairy',
    icon: '🥛',
    subCategories: [
      PantrySubCategory(
        title: 'Milk',
        items: [
          'Whole Milk',
          '2% Milk',
          'Skim Milk',
          '1% Milk',
          'Almond Milk',
          'Oat Milk',
          'Soy Milk',
          'Coconut Milk',
          'Cashew Milk',
          'Lactose-Free Milk',
        ],
      ),
      PantrySubCategory(
        title: 'Cheese',
        items: [
          'Cheddar Cheese',
          'Mozzarella Cheese',
          'Parmesan Cheese',
          'Feta Cheese',
          'Cream Cheese',
          'Swiss Cheese',
          'Provolone Cheese',
          'Gouda Cheese',
          'Brie Cheese',
          'Blue Cheese',
          'Goat Cheese',
          'Ricotta Cheese',
          'Cottage Cheese',
          'Monterey Jack',
          'Pepper Jack',
          'Colby Jack',
          'American Cheese',
          'String Cheese',
        ],
      ),
      PantrySubCategory(
        title: 'Yogurt',
        items: [
          'Greek Yogurt',
          'Plain Yogurt',
          'Vanilla Yogurt',
          'Strawberry Yogurt',
          'Blueberry Yogurt',
          'Peach Yogurt',
          'Skyr',
          'Kefir',
        ],
      ),
      PantrySubCategory(
        title: 'Eggs',
        items: ['Large Eggs', 'Egg Whites', 'Egg Beaters'],
      ),
      PantrySubCategory(
        title: 'Cream & Butter',
        items: [
          'Heavy Cream',
          'Whipping Cream',
          'Sour Cream',
          'Half & Half',
          'Salted Butter',
          'Unsalted Butter',
          'Margarine',
          'Ghee',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Grains & Baking',
    icon: '🍞',
    subCategories: [
      PantrySubCategory(
        title: 'Flour',
        items: [
          'All-Purpose Flour',
          'Bread Flour',
          'Whole Wheat Flour',
          'Almond Flour',
          'Coconut Flour',
          'Cake Flour',
          'Self-Rising Flour',
          'Rye Flour',
        ],
      ),
      PantrySubCategory(
        title: 'Rice',
        items: [
          'White Rice',
          'Brown Rice',
          'Basmati Rice',
          'Jasmine Rice',
          'Arborio Rice',
          'Wild Rice',
          'Sushi Rice',
          'Instant Rice',
        ],
      ),
      PantrySubCategory(
        title: 'Pasta',
        items: [
          'Spaghetti',
          'Penne',
          'Fusilli',
          'Macaroni',
          'Fettuccine',
          'Linguine',
          'Rigatoni',
          'Farfalle',
          'Angel Hair',
          'Lasagna Noodles',
          'Ravioli',
          'Tortellini',
        ],
      ),
      PantrySubCategory(
        title: 'Bread',
        items: [
          'White Bread',
          'Whole Wheat Bread',
          'Sourdough',
          'Rye Bread',
          'Bagels',
          'English Muffins',
          'Pita Bread',
          'Naan',
          'Tortillas',
          'Flour Tortillas',
          'Corn Tortillas',
          'Buns',
          'Rolls',
          'Baguette',
          'Ciabatta',
        ],
      ),
      PantrySubCategory(
        title: 'Baking Essentials',
        items: [
          'White Sugar',
          'Brown Sugar',
          'Powdered Sugar',
          'Baking Powder',
          'Baking Soda',
          'Active Dry Yeast',
          'Instant Yeast',
          'Vanilla Extract',
          'Chocolate Chips',
          'Cocoa Powder',
          'Cornstarch',
          'Honey',
          'Maple Syrup',
          'Molasses',
          'Corn Syrup',
        ],
      ),
      PantrySubCategory(
        title: 'Oats & Cereals',
        items: [
          'Rolled Oats',
          'Instant Oats',
          'Steel Cut Oats',
          'Quinoa',
          'Couscous',
          'Bulgur',
          'Farro',
          'Barley',
          'Cornmeal',
          'Polenta',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Pantry Staples',
    icon: '🥫',
    subCategories: [
      PantrySubCategory(
        title: 'Oils & Vinegars',
        items: [
          'Olive Oil',
          'Extra Virgin Olive Oil',
          'Vegetable Oil',
          'Canola Oil',
          'Coconut Oil',
          'Sesame Oil',
          'Avocado Oil',
          'Peanut Oil',
          'White Vinegar',
          'Apple Cider Vinegar',
          'Balsamic Vinegar',
          'Red Wine Vinegar',
          'Rice Vinegar',
        ],
      ),
      PantrySubCategory(
        title: 'Condiments',
        items: [
          'Ketchup',
          'Mustard',
          'Yellow Mustard',
          'Dijon Mustard',
          'Mayonnaise',
          'Soy Sauce',
          'Hot Sauce',
          'Sriracha',
          'BBQ Sauce',
          'Worcestershire Sauce',
          'Fish Sauce',
          'Oyster Sauce',
          'Hoisin Sauce',
          'Teriyaki Sauce',
          'Ranch Dressing',
          'Italian Dressing',
          'Caesar Dressing',
          'Salsa',
          'Pesto',
          'Tahini',
          'Hummus',
        ],
      ),
      PantrySubCategory(
        title: 'Canned Goods',
        items: [
          'Black Beans',
          'Kidney Beans',
          'Pinto Beans',
          'Chickpeas',
          'Refried Beans',
          'Diced Tomatoes',
          'Crushed Tomatoes',
          'Tomato Paste',
          'Tomato Sauce',
          'Corn',
          'Green Beans',
          'Chicken Noodle Soup',
          'Tomato Soup',
          'Cream of Mushroom Soup',
          'Tuna',
          'Salmon',
          'Sardines',
          'Coconut Milk',
          'Evaporated Milk',
          'Condensed Milk',
        ],
      ),
      PantrySubCategory(
        title: 'Spices & Herbs',
        items: [
          'Salt',
          'Black Pepper',
          'Garlic Powder',
          'Onion Powder',
          'Cumin',
          'Paprika',
          'Smoked Paprika',
          'Chili Powder',
          'Cayenne Pepper',
          'Cinnamon',
          'Nutmeg',
          'Ginger',
          'Turmeric',
          'Oregano',
          'Basil',
          'Thyme',
          'Rosemary',
          'Parsley',
          'Cilantro',
          'Dill',
          'Bay Leaves',
          'Red Pepper Flakes',
          'Italian Seasoning',
          'Curry Powder',
          'Coriander',
          'Cardamom',
          'Cloves',
          'Allspice',
        ],
      ),
      PantrySubCategory(
        title: 'Broth & Stock',
        items: [
          'Chicken Broth',
          'Beef Broth',
          'Vegetable Broth',
          'Chicken Stock',
          'Beef Stock',
          'Bone Broth',
        ],
      ),
      PantrySubCategory(
        title: 'Nuts & Seeds',
        items: [
          'Almonds',
          'Peanuts',
          'Cashews',
          'Walnuts',
          'Pecans',
          'Pistachios',
          'Hazelnuts',
          'Macadamia Nuts',
          'Pine Nuts',
          'Sunflower Seeds',
          'Pumpkin Seeds',
          'Chia Seeds',
          'Flax Seeds',
          'Sesame Seeds',
          'Peanut Butter',
          'Almond Butter',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Frozen',
    icon: '❄️',
    subCategories: [
      PantrySubCategory(
        title: 'Frozen Vegetables',
        items: [
          'Frozen Peas',
          'Frozen Corn',
          'Frozen Mixed Vegetables',
          'Frozen Spinach',
          'Frozen Broccoli',
          'Frozen Cauliflower',
          'Frozen Green Beans',
          'Frozen Carrots',
          'Frozen Brussels Sprouts',
          'Frozen Edamame',
          'Frozen Stir Fry Mix',
        ],
      ),
      PantrySubCategory(
        title: 'Frozen Fruits',
        items: [
          'Frozen Strawberries',
          'Frozen Blueberries',
          'Frozen Mixed Berries',
          'Frozen Mango',
          'Frozen Peaches',
          'Frozen Pineapple',
          'Frozen Raspberries',
        ],
      ),
      PantrySubCategory(
        title: 'Frozen Meals',
        items: [
          'Frozen Pizza',
          'TV Dinners',
          'Frozen Burritos',
          'Frozen Chicken Nuggets',
          'Frozen Fish Sticks',
          'Frozen Meatballs',
          'Frozen Dumplings',
          'Frozen Pot Pies',
        ],
      ),
      PantrySubCategory(
        title: 'Frozen Desserts',
        items: [
          'Vanilla Ice Cream',
          'Chocolate Ice Cream',
          'Strawberry Ice Cream',
          'Popsicles',
          'Frozen Yogurt',
          'Sorbet',
          'Ice Cream Sandwiches',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Snacks',
    icon: '🍿',
    subCategories: [
      PantrySubCategory(
        title: 'Chips & Crisps',
        items: [
          'Potato Chips',
          'Tortilla Chips',
          'Corn Chips',
          'Pretzels',
          'Pita Chips',
          'Veggie Chips',
          'Popcorn',
        ],
      ),
      PantrySubCategory(
        title: 'Crackers',
        items: [
          'Saltine Crackers',
          'Wheat Thins',
          'Ritz Crackers',
          'Graham Crackers',
          'Cheese Crackers',
          'Rice Cakes',
        ],
      ),
      PantrySubCategory(
        title: 'Sweets',
        items: [
          'Chocolate Chip Cookies',
          'Oreos',
          'Brownies',
          'Candy Bars',
          'Gummy Bears',
          'Chocolate',
          'Dark Chocolate',
          'Milk Chocolate',
          'M&Ms',
          'Skittles',
        ],
      ),
      PantrySubCategory(
        title: 'Bars',
        items: ['Granola Bars', 'Protein Bars', 'Energy Bars', 'Cereal Bars'],
      ),
    ],
  ),
  PantryCategory(
    title: 'Beverages',
    icon: '🥤',
    subCategories: [
      PantrySubCategory(
        title: 'Water',
        items: ['Bottled Water', 'Sparkling Water', 'Flavored Water'],
      ),
      PantrySubCategory(
        title: 'Soda',
        items: [
          'Coca-Cola',
          'Pepsi',
          'Sprite',
          'Mountain Dew',
          'Dr Pepper',
          'Root Beer',
          'Ginger Ale',
        ],
      ),
      PantrySubCategory(
        title: 'Juice',
        items: [
          'Orange Juice',
          'Apple Juice',
          'Grape Juice',
          'Cranberry Juice',
          'Pineapple Juice',
          'Lemonade',
          'Fruit Punch',
        ],
      ),
      PantrySubCategory(
        title: 'Coffee & Tea',
        items: [
          'Ground Coffee',
          'Instant Coffee',
          'Coffee Beans',
          'Black Tea',
          'Green Tea',
          'Herbal Tea',
          'Chai Tea',
          'Earl Grey Tea',
        ],
      ),
      PantrySubCategory(
        title: 'Alcohol',
        items: [
          'Beer',
          'Red Wine',
          'White Wine',
          'Vodka',
          'Whiskey',
          'Rum',
          'Tequila',
          'Gin',
        ],
      ),
      PantrySubCategory(
        title: 'Other Drinks',
        items: [
          'Energy Drinks',
          'Sports Drinks',
          'Protein Shakes',
          'Smoothies',
        ],
      ),
    ],
  ),
  PantryCategory(
    title: 'Other',
    icon: '📦',
    subCategories: [
      PantrySubCategory(
        title: 'Miscellaneous',
        items: [
          'Pet Food',
          'Paper Towels',
          'Toilet Paper',
          'Dish Soap',
          'Laundry Detergent',
          'Trash Bags',
        ],
      ),
    ],
  ),
];
